# Generated by Django 4.2.1 on 2023-05-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phonr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='phonr',
        ),
    ]
